### ISSUE TITLE
EPIC: CI process

### ISSUE THREAD

**Issue by lukasz-zimnoch** [mezo-org/mezod#118]
The goal of this epic is developing a CI process adjusted to our needs. That includes:
- Auditing existing CI jobs
- Cleaning up unnecessary jobs
- Adjusting and fixing the remaining jobs
- Creating new jobs according to the needs

```[tasklist]
### Tasks
- [ ] https://github.com/thesis/mezo/issues/28
- [ ] https://github.com/thesis/mezo/issues/38
- [ ] https://github.com/thesis/mezo/issues/37
- [ ] https://github.com/thesis/mezo/issues/33
- [ ] https://github.com/thesis/mezo/issues/149
- [ ] https://github.com/thesis/mezo/issues/158
- [ ] https://github.com/thesis/mezo/issues/164
```
