### ISSUE TITLE
Precompiled BTC ERC20 contract

### ISSUE THREAD

**Issue by lukasz-zimnoch** [mezo-org/mezod#121]
Depends on: https://github.com/thesis/mezo/issues/120

This task is about creating a precompiled ERC20 contract for the TBTC token. This precompile should implement the same [interface as the TBTC token on Ethereum does](https://github.com/keep-network/tbtc-v2/blob/main/solidity/contracts/token/TBTC.sol), except for the misfund recovery functionality. We also need to make sure this token is correctly set as Mezo gas token. Last but not least, let's reserve the BTC precompile address in the `x/evm` module's genesis by putting a dummy code for that contract in the state DB (see [this Discord discussion](https://discord.com/channels/1079490158639976609/1249675303870267402/1252223895919136778) for reference)
```[tasklist]
### Tasks
- [ ] https://github.com/thesis/mezo/pull/140
- [ ] https://github.com/thesis/mezo/pull/178
- [ ] https://github.com/thesis/mezo/pull/180
- [ ] https://github.com/thesis/mezo/pull/189
- [ ] https://github.com/thesis/mezo/pull/192
- [ ] https://github.com/thesis/mezo/pull/210
- [ ] https://github.com/thesis/mezo/pull/214
- [ ] https://github.com/thesis/mezo/pull/222
- [ ] https://github.com/thesis/mezo/pull/235
- [ ] https://github.com/thesis/mezo/pull/239
```
