### ISSUE TITLE
EPIC: Proof of Authority

### ISSUE THREAD

**Issue by lukasz-zimnoch** [mezo-org/mezod#151]
Specification: [Proof of Authority product pitch](https://coda.io/d/_d_vIDNPK008#Draft-Product-Pitches_tuH_B/r82)

```[tasklist]
### Tasks
- [ ] https://github.com/thesis/mezo/issues/152
- [ ] https://github.com/thesis/mezo/issues/154
- [ ] https://github.com/thesis/mezo/issues/155
- [ ] https://github.com/thesis/mezo/issues/224
- [ ] E2E tests for PoA
- [ ] Documentation for PoA
```
