### ISSUE TITLE
Integrate `lumtis/poa` PoA module

### ISSUE THREAD

**Issue by lukasz-zimnoch** [mezo-org/mezod#154]
This task is about integrating the https://github.com/lumtis/poa module with Mezo codebase. Specific steps are:
- Port https://github.com/lumtis/poa as a new `x/poa` module
- Adjust `x/poa` to the newer Cosmos SDK version used by Mezo
- Use `x/poa` to replace the existing Cosmos `x/staking` module
- Go through all modules that depends on `x/staking` and decide about their fate
- Adjust the `x/poa` module according to our requirements
- Adjust all deployment and infrastructure scripts accordingly
- Deploy on internal testnet and execute some test scenarios
```[tasklist]
### Tasks
- [ ] https://github.com/thesis/mezo/pull/177
- [ ] https://github.com/thesis/mezo/pull/179
- [ ] https://github.com/thesis/mezo/pull/194
- [ ] https://github.com/thesis/mezo/pull/195
- [ ] https://github.com/thesis/mezo/pull/207
```
