### ISSUE TITLE
Implement the bridge core with ABCI++

### ISSUE THREAD

**Issue by lukasz-zimnoch** [mezo-org/mezod#254]
This task captures the work around implementing the bridge's core in the `x/bridge` module (developed in #161) and setting up ABCI++ hooks to integrate it with the consensus engine. Details are specified in the [`x/bridge`](https://github.com/thesis/mezo/blob/main/docs/rfc/rfc-2.md#xbridge) and [Consensus](https://github.com/thesis/mezo/blob/main/docs/rfc/rfc-2.md#consensus) sections of RFC-2.
```[tasklist]
### Tasks
- [ ] https://github.com/thesis/mezo/pull/258
- [ ] https://github.com/mezo-org/mezod/pull/262
- [ ] https://github.com/mezo-org/mezod/pull/283
- [ ] https://github.com/mezo-org/mezod/pull/294
```
