### ISSUE TITLE
Fix CI build jobs

### ISSUE THREAD

**Issue by pdyraga** [mezo-org/mezod#28]
Two jobs are failing for pull requests:
- Run Gosec / Gosec (pull_request), 
- Semgrep / Scan (pull_request).

We need to inspect the reason and fix those jobs. As a part of the work on this issue, we should also inspect the rest of the jobs and confirm there is nothing unexpected there like, for example, uploading data to remote locations controlled by the upstream repository.
```[tasklist]
### Tasks
- [ ] https://github.com/thesis/mezo/pull/31
- [ ] https://github.com/thesis/mezo/pull/80
- [ ] https://github.com/thesis/mezo/pull/143
- [ ] https://github.com/thesis/mezo/pull/146
- [ ] https://github.com/thesis/mezo/pull/148
- [ ] https://github.com/thesis/mezo/pull/150
- [ ] https://github.com/thesis/mezo/pull/145
- [ ] https://github.com/thesis/mezo/pull/156/
```
