### ISSUE TITLE
EPIC: Basic internal testnet with block explorer and Bitcoin being the native asset

### ISSUE THREAD

**Issue by pdyraga** [mezo-org/mezod#34]
We want Bitcoin to be used as a base token for the gas fees but also like an ERC20 on EVM. This will require a rename, checking denomination precisions, and adjusting them.
```[tasklist]
### Tasks
- [ ] https://github.com/thesis/meso/issues/36
- [ ] https://github.com/thesis/meso/issues/35
- [ ] https://github.com/thesis/mezo/pull/85
- [ ] https://github.com/thesis/mezo/issues/86
- [ ] https://github.com/thesis/mezo/issues/98
- [ ] https://github.com/thesis/mezo/issues/188
- [ ] https://github.com/thesis/mezo/issues/117
```
