### ISSUE TITLE
Setup testnet infrastructure

### ISSUE THREAD

**Issue by lukasz-zimnoch** [mezo-org/mezod#86]
This task captures the work required to setup testnet infrastructure on GCP.
```[tasklist]
### Tasks
- [ ] https://github.com/thesis/mezo/pull/88
- [ ] https://github.com/thesis/mezo/pull/96
- [ ] https://github.com/thesis/mezo/pull/106
- [ ] https://github.com/thesis/mezo/pull/112
```
